name: "Build and Tests"
on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: "Install dependencies"
        run: opam install . --deps-only --with-test

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v2

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
